# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [2]:
s="hi there sam!"
a=s.split()
print(a);

['hi', 'there', 'sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [3]:
planet="earth"
diameter=12742
print('the diameter of {} is {} killometers.'. format(planet, diameter));

the diameter of earth is 12742 killometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [4]:
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [5]:
import numpy as np
array=np.zeros(10)*2
print("an array of 10 zero")
print(array)

an array of 10 zero
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
array=np.ones(10)*5
print("an array of 10 five")
print(array)

## 5. Create an array of all the even integers from 20 to 35

In [6]:
import numpy as np
array=np.arange(20,35)
print("array of all the even integers from 20 to 35")
print(array)

array of all the even integers from 20 to 35
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
import numpy as np
array_2D=np.identity(3)
print('3*3 matrix:')
print(array_2D)

3*3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [8]:
import numpy as np
a=np.array([1,2,3])
b=np.array ([4,5,6])
c=a+b,a*b,a-b
print(c)

(array([5, 7, 9]), array([ 4, 10, 18]), array([-3, -3, -3]))


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [9]:
import pandas as pd
data = [10,20,30,40,50,60]
df = pd.DataFrame(data, columns=['Numbers'])
df

Numbers
0       10
1       20
2       30
3       40
4       50
5       60

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [19]:
import datetime
start_date=datetime.date(2023,1,1)
end_date=datetime.date(2023,2,10)
delta = datetime.timedelta(days=1)
while (start_date<=end_date):
    print(start_date,end="\n")
    start_date+=delta

2023-01-01
2023-01-02
2023-01-03
2023-01-04
2023-01-05
2023-01-06
2023-01-07
2023-01-08
2023-01-09
2023-01-10
2023-01-11
2023-01-12
2023-01-13
2023-01-14
2023-01-15
2023-01-16
2023-01-17
2023-01-18
2023-01-19
2023-01-20
2023-01-21
2023-01-22
2023-01-23
2023-01-24
2023-01-25
2023-01-26
2023-01-27
2023-01-28
2023-01-29
2023-01-30
2023-01-31
2023-02-01
2023-02-02
2023-02-03
2023-02-04
2023-02-05
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [21]:
import pandas as pd
lists={'s.no':["1","2","3"],'name':["aaa","bbb","ccc"],'age':[22,25,24]}
df=pd.DataFrame(lists)
print(df)

  s.no name  age
0    1  aaa   22
1    2  bbb   25
2    3  ccc   24
