# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [2]:
s="hi there sam!"
a=s.split()
print(a);

['hi', 'there', 'sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [3]:
planet="earth"
diameter=12742
print('the diameter of {} is {} killometers.'. format(planet, diameter));

the diameter of earth is 12742 killometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [4]:
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [5]:
import numpy as np
array=np.zeros(10)*2
print("an array of 10 zero")
print(array)

an array of 10 zero
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
import numpy as np
array=np.ones(10)*5
print("an array of 10 five")
print(array)

an array of 10 five
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [8]:
import numpy as np
array=np.arange(20,35)
print("array of all the even integers from 20 to 35")
print(array)

array of all the even integers from 20 to 35
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
import numpy as np
array_2D=np.identity(3)
print('3*3 matrix:')
print(array_2D)

3*3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [10]:
import numpy as np
a=np.array([1,2,3])
b=np.array ([4,5,6])
c=a+b,a*b,a-b
print(c)

(array([5, 7, 9]), array([ 4, 10, 18]), array([-3, -3, -3]))


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [3]:
import pandas as pd
data = [10,20,30,40,50,60]
df = pd.DataFrame(data, columns=['Numbers'])
df

Numbers
0       10
1       20
2       30
3       40
4       50
5       60

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [14]:
import timedelta,data
def daterange(date1,date2):
    for n if in_range(int((date2-date).days)+1):
        yield date1+timedelta(n)
        start_dt=date(2023-1-1)
        end_dt=date=date(2023-10-2)
    for dt in daterange(start_dt,end_dt);
        print9dt.strftime("yy-%m-%d")
       

SyntaxError: invalid syntax (2145065431.py, line 3)

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [5]:
import pandas as pd

# List1
list=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
df=pd.DataFrame(list, columns =['FName', 'LName', 'Age'], dtype =float )
print(df)


   FName LName   Age
0    1.0   aaa  22.0
1    2.0   bbb  25.0
2    3.0   ccc  24.0


C:\Users\GUNALRAJ\AppData\Local\Temp\ipykernel_8336\3109132565.py:5: FutureWarning: Could not cast to float64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised.
  df=pd.DataFrame(list, columns =['FName', 'LName', 'Age'], dtype =float )
